Layout/EndOfLine:
  EnforcedStyle: lf
Layout/FirstHashElementIndentation:
  EnforcedStyle: consistent
Layout/LineLength:
  Max: 120
  IgnoreCopDirectives: true

Metrics/ClassLength:
  Max: 300
Metrics/MethodLength:
  Max: 30
Metrics/ParameterLists:   # keep limit of 5 for positional arguments
  CountKeywordArgs: false # but allow unlimited named parameters to encourage explicit options

Style/Documentation:
  Enabled: false
Style/CollectionMethods:
  Enabled: true
Style/EmptyMethod:
  EnforcedStyle: expanded
Style/OptionHash: # prefer explicitly named keyword parameters
  Enabled: true
Style/RegexpLiteral:
  EnforcedStyle: slashes
  AllowInnerSlashes: true
Style/SymbolArray:
  EnforcedStyle: brackets
Style/WordArray:
  EnforcedStyle: brackets
