Layout/EndOfLine:
  EnforcedStyle: lf
Layout/FirstHashElementIndentation:
  EnforcedStyle: consistent
Layout/LineLength:
  Max: 120
  IgnoreCopDirectives: true

Metrics/ClassLength:
  Max: 300
Metrics/MethodLength:
  Max: 30
Metrics/ParameterLists:   # keep limit of 5 for positional arguments
  CountKeywordArgs: false # but allow unlimited named parameters to encourage explicit options
Metrics/AbcSize:
  Max: 35
Metrics/CyclomaticComplexity:
  Max: 10
Metrics/PerceivedComplexity:
  Max: 10

Style/ConditionalAssignment:
  Enabled: false # assign_inside_condition if any
Style/Documentation:
  Enabled: false
Style/CollectionMethods:
  Enabled: true
Style/EmptyMethod:
  EnforcedStyle: expanded
Style/OptionHash: # prefer explicitly named keyword parameters
  Enabled: true
Style/RegexpLiteral:
  EnforcedStyle: slashes
  AllowInnerSlashes: true
Style/SymbolArray:
  EnforcedStyle: brackets
Style/WordArray:
  EnforcedStyle: brackets
Style/OpenStructUse:
  Enabled: false

Gemspec/RequireMFA:
  Enabled: false

Naming/VariableNumber:
  Enabled: false
