Layout/EndOfLine:
  EnforcedStyle: lf
Layout/FirstHashElementIndentation:
  EnforcedStyle: consistent
Layout/LineLength:
  Max: 150
  IgnoreCopDirectives: true
Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Metrics/ClassLength:
  Max: 300
Metrics/MethodLength:
  Max: 30
Metrics/ParameterLists: # keep limit of 5 for positional arguments
  CountKeywordArgs: false # but allow unlimited named parameters to encourage explicit options
Metrics/AbcSize:
  Max: 35
Metrics/CyclomaticComplexity:
  Max: 10
Metrics/PerceivedComplexity:
  Max: 10

Style/ConditionalAssignment:
  Enabled: false # this rule is dumb b/c it also includes (.. ? .. : ..) who would want to assign inside the condition here???
  # EnforcedStyle: assign_inside_condition
Style/Documentation:
  Enabled: false
Style/CollectionMethods:
  Enabled: true
Style/EmptyMethod:
  EnforcedStyle: expanded
Style/OptionHash: # prefer explicitly named keyword parameters
  Enabled: true
Style/RegexpLiteral:
  EnforcedStyle: slashes
  AllowInnerSlashes: true
Style/SymbolArray:
  EnforcedStyle: brackets
Style/WordArray:
  EnforcedStyle: brackets
Style/OpenStructUse:
  Enabled: false
Style/YodaExpression:
  Enabled: false

Gemspec/RequireMFA:
  Enabled: false

Naming/VariableNumber:
  Enabled: false
# while i agree with this, we should use `?` for methods that return a boolean 
# if the method does other stuff and happens to return a boolean we should NOT use `?`
# so disabling this b/c its a terrible check
Naming/PredicateMethod:
  Enabled: false 